services:
  backend:
    build:
      context: .
    container_name: file-trans-backend
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./uploads:/app/uploads
    expose:
      - "17878"

  frontend:
    build:
      context: ../frontend
    container_name: file-trans-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "17878:80"
